# Import Ubuntu image to Docker
FROM ubuntu:18.04

# Shares Volume
#VOLUME ["docker"]

# Install lists
RUN apt-get update && apt-get install -y \
    build-essential clang flex g++ gawk gettext git libncurses5-dev libssl-dev \
    python3 rsync unzip zlib1g-dev pkg-config vim tree net-tools wireless-tools wget \
	iputils-ping uuid-dev libjsoncpp-dev automake gcc-aarch64-linux-gnu gcc-7-aarch64-linux-gnu \
	bison bc device-tree-compiler

# Downloading and installing binary

#USER
#USER elwin

# Downloading and installing binary
RUN ln -s  /usr/include/jsoncpp/json/ /usr/include/json
